In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train.csv")

In [3]:
df.head(20)

ID  Customer_ID  Month             Name   Age          SSN Occupation  \
0   5634         3392      1    Aaron Maashoh  23.0  821000265.0  Scientist   
1   5635         3392      2    Aaron Maashoh  23.0  821000265.0  Scientist   
2   5636         3392      3    Aaron Maashoh  23.0  821000265.0  Scientist   
3   5637         3392      4    Aaron Maashoh  23.0  821000265.0  Scientist   
4   5638         3392      5    Aaron Maashoh  23.0  821000265.0  Scientist   
5   5639         3392      6    Aaron Maashoh  23.0  821000265.0  Scientist   
6   5640         3392      7    Aaron Maashoh  23.0  821000265.0  Scientist   
7   5641         3392      8    Aaron Maashoh  23.0  821000265.0  Scientist   
8   5646         8625      1  Rick Rothackerj  28.0    4075839.0    Teacher   
9   5647         8625      2  Rick Rothackerj  28.0    4075839.0    Teacher   
10  5648         8625      3  Rick Rothackerj  28.0    4075839.0    Teacher   
11  5649         8625      4  Rick Rothackerj  28.0    4075839.0    Teacher   
12  5650         8625      5  Rick Rothackerj  28.0    4075839.0    Teacher   
13  5651         8625      6  Rick Rothackerj  28.0    4075839.0    Teacher   
14  5652         8625      7  Rick Rothackerj  28.0    4075839.0    Teacher   
15  5653         8625      8  Rick Rothackerj  28.0    4075839.0    Teacher   
16  5658        11708      1           Langep  34.0  486853974.0   Engineer   
17  5659        11708      2           Langep  34.0  486853974.0   Engineer   
18  5660        11708      3           Langep  34.0  486853974.0   Engineer   
19  5661        11708      4           Langep  34.0  486853974.0   Engineer   

    Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  Credit_Mix  \
0        19114.12            1824.843333                3.0  ...        Good   
1        19114.12            1824.843333                3.0  ...        Good   
2        19114.12            1824.843333                3.0  ...        Good   
3        19114.12            1824.843333                3.0  ...        Good   
4        19114.12            1824.843333                3.0  ...        Good   
5        19114.12            1824.843333                3.0  ...        Good   
6        19114.12            1824.843333                3.0  ...        Good   
7        19114.12            1824.843333                3.0  ...        Good   
8        34847.84            3037.986667                2.0  ...        Good   
9        34847.84            3037.986667                2.0  ...        Good   
10       34847.84            3037.986667                2.0  ...        Good   
11       34847.84            3037.986667                2.0  ...        Good   
12       34847.84            3037.986667                2.0  ...        Good   
13       34847.84            3037.986667                2.0  ...        Good   
14       34847.84            3037.986667                2.0  ...        Good   
15       34847.84            3037.986667                2.0  ...        Good   
16      143162.64           12187.220000                1.0  ...        Good   
17      143162.64           12187.220000                1.0  ...        Good   
18      143162.64           12187.220000                1.0  ...        Good   
19      143162.64           12187.220000                1.0  ...        Good   

    Outstanding_Debt  Credit_Utilization_Ratio Credit_History_Age  \
0             809.98                 26.822620              265.0   
1             809.98                 31.944960              266.0   
2             809.98                 28.609352              267.0   
3             809.98                 31.377862              268.0   
4             809.98                 24.797347              269.0   
5             809.98                 27.262259              270.0   
6             809.98                 22.537593              271.0   
7             809.98                 23.933795              272.0   
8             605.03                 24.4640

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   ID                        100000 non-null  int64  
 1   Customer_ID               100000 non-null  int64  
 2   Month                     100000 non-null  int64  
 3   Name                      100000 non-null  object 
 4   Age                       100000 non-null  float64
 5   SSN                       100000 non-null  float64
 6   Occupation                100000 non-null  object 
 7   Annual_Income             100000 non-null  float64
 8   Monthly_Inhand_Salary     100000 non-null  float64
 9   Num_Bank_Accounts         100000 non-null  float64
 10  Num_Credit_Card           100000 non-null  float64
 11  Interest_Rate             100000 non-null  float64
 12  Num_of_Loan               100000 non-null  float64
 13  Type_of_Loan              100000 non-null  ob

In [5]:
df.shape

(100000, 28)

In [6]:
df.describe()

ID    Customer_ID          Month            Age  \
count  100000.000000  100000.000000  100000.000000  100000.000000   
mean    80631.500000   25982.666640       4.500000      33.316340   
std     43301.486619   14340.543051       2.291299      10.764812   
min      5634.000000    1006.000000       1.000000      14.000000   
25%     43132.750000   13664.500000       2.750000      24.000000   
50%     80631.500000   25777.000000       4.500000      33.000000   
75%    118130.250000   38385.000000       6.250000      42.000000   
max    155629.000000   50999.000000       8.000000      56.000000   

                SSN  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
count  1.000000e+05  100000.000000          100000.000000      100000.000000   
mean   5.004617e+08   50505.123449            4197.270835           5.368820   
std    2.908267e+08   38299.422093            3186.432497           2.593314   
min    8.134900e+04    7005.930000             303.645417           0.000000   
25%    2.451686e+08   19342.972500            1626.594167           3.000000   
50%    5.006886e+08   36999.705000            3095.905000           5.000000   
75%    7.560027e+08   71683.470000            5957.715000           7.000000   
max    9.999934e+08  179987.280000           15204.633333          11.000000   

       Num_Credit_Card  Interest_Rate  ...  Delay_from_due_date  \
count    100000.000000   100000.00000  ...         100000.00000   
mean          5.533570       14.53208  ...             21.08141   
std           2.067098        8.74133  ...             14.80456   
min           0.000000        1.00000  ...              0.00000   
25%           4.000000        7.00000  ...             10.00000   
50%           5.000000       13.00000  ...             18.00000   
75%           7.000000       20.00000  ...             28.00000   
max          11.000000       34.00000  ...             62.00000   

       Num_of_Delayed_Payment  Changed_Credit_Limit  Num_Credit_Inquiries  \
count           100000.000000         100000.000000         100000.000000   
mean                13.313120             10.470323              5.798250   
std                  6.237166              6.609481              3.867826   
min                  0.000000              0.500000              0.000000   
25%                  9.000000              5.380000              3.000000   
50%                 14.000000              9.400000              5.000000   
75%                 18.000000             14.850000              8.000000   
max                 25.000000             29.980000             17.000000   

       Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
count     100000.000000             100000.000000       100000.000000   
mean        1426.220376                 32.285173          221.220460   
std         1155.129026                  5.116875           99.680716   
min            0.230000                 20.000000            1.000000   
25%          566.072500                 28.052567          144.000000   
50%         1166.155000                 32.305784          219.000000   
75%         1945.962500                 36.496663          302.000000   
max         4998.070000                 50.000000          404.000000   

       Total_EMI_per_month  Amount_invested_monthly  Monthly_Balance  
count        100000.000000            100000.000000    100000.000000  
mean            107.699208                55.101315       392.697586  
std             132.267056                39.006932       201.652719  
min               0.000000                 0.000000         0.007760  
25%              29.268886                27.959111       267.615983  
50%              66.462304                45.156550       333.865366  
75%             147.392573                71.295797       463.215683  
max            1779.103254               434.191089      1183.930696  

[8 rows x 21 columns]

In [7]:
numb = df['Occupation'].value_counts()

print(numb)

Lawyer           7096
Engineer         6864
Architect        6824
Mechanic         6776
Scientist        6744
Accountant       6744
Developer        6720
Media_Manager    6720
Teacher          6672
Entrepreneur     6648
Doctor           6568
Journalist       6536
Manager          6432
Musician         6352
Writer           6304
Name: Occupation, dtype: int64


In [8]:
numb = df['Credit_Mix'].value_counts()

print(numb)

Standard    45848
Good        30384
Bad         23768
Name: Credit_Mix, dtype: int64


In [9]:

numb = df['Payment_of_Min_Amount'].value_counts()

print(numb)

Yes    52326
No     35667
NM     12007
Name: Payment_of_Min_Amount, dtype: int64


In [10]:

numb = df['Payment_Behaviour'].value_counts()

print(numb)

Low_spent_Small_value_payments      28616
High_spent_Medium_value_payments    19738
High_spent_Large_value_payments     14726
Low_spent_Medium_value_payments     14399
High_spent_Small_value_payments     11764
Low_spent_Large_value_payments      10757
Name: Payment_Behaviour, dtype: int64


In [11]:

numb = df['Credit_Score'].value_counts()

print(numb)

Standard    53174
Poor        28998
Good        17828
Name: Credit_Score, dtype: int64


In [12]:
df.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [13]:
for column in df.columns:
    if column != 'ID': 
        value_counts = df[column].value_counts()
        num_categories = len(value_counts)
        
        # İki alt kategorisi varsa 0 ve 1 olarak kodlayalım
        if num_categories == 2:
            category_mapping = {category: index for index, category in enumerate(value_counts.index)}
            df[column] = df[column].map(category_mapping)
        # İki alt kategoriden fazlaysa 1'den başlayan sıralı sayılarla kodlayalım
        else:
            category_mapping = {category: index + 1 for index, category in enumerate(value_counts.index)}
            df[column] = df[column].map(category_mapping)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  int64
 1   Customer_ID               100000 non-null  int64
 2   Month                     100000 non-null  int64
 3   Name                      100000 non-null  int64
 4   Age                       100000 non-null  int64
 5   SSN                       100000 non-null  int64
 6   Occupation                100000 non-null  int64
 7   Annual_Income             100000 non-null  int64
 8   Monthly_Inhand_Salary     100000 non-null  int64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  int64
 13  Type_of_Loan              100000 non-null  int64
 14  Delay_from_due_date  

In [18]:
import numpy as np

In [22]:
from sklearn.model_selection import train_test_split
x = np.array(df[['Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance']])
y = np.array(df[["Credit_Score"]])

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                test_size=0.10, 
                                                random_state=42)

In [23]:
print(df.columns)

Index(['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')


In [24]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((90000, 25), (10000, 25), (90000, 1), (10000, 1))

In [25]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
g=GaussianNB()
b=BernoulliNB()
g.fit(x,y)
b.fit(x,y)
tahmin1=g.predict(x)
tahmin2=b.predict(x)

/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [27]:
accuracy_score(tahmin1,y)

0.61438

In [28]:
accuracy_score(tahmin2,y)

0.53174

In [29]:
confusion_matrix(tahmin1,y)

array([[33357,  8458,  6095],
       [ 9994, 16828,   480],
       [ 9823,  3712, 11253]])

In [30]:
confusion_matrix(tahmin2,y)

array([[53174, 28998, 17828],
       [    0,     0,     0],
       [    0,     0,     0]])

In [31]:
from sklearn.metrics import precision_score, recall_score

In [32]:
print(classification_report(tahmin1,y))

              precision    recall  f1-score   support

           1       0.63      0.70      0.66     47910
           2       0.58      0.62      0.60     27302
           3       0.63      0.45      0.53     24788

    accuracy                           0.61    100000
   macro avg       0.61      0.59      0.60    100000
weighted avg       0.62      0.61      0.61    100000



In [33]:
print(classification_report(tahmin2,y))

              precision    recall  f1-score   support

           1       1.00      0.53      0.69    100000
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

    accuracy                           0.53    100000
   macro avg       0.33      0.18      0.23    100000
weighted avg       1.00      0.53      0.69    100000



/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
from sklearn.neighbors import KNeighborsClassifier
k=KNeighborsClassifier()
k.fit(x,y)

/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [36]:
tahmin3=k.predict(x)


In [37]:
accuracy_score(tahmin3,y)

0.83104

In [38]:
confusion_matrix(tahmin3,y)

array([[44088,  3982,  3310],
       [ 5682, 24841,   343],
       [ 3404,   175, 14175]])

In [39]:
print(classification_report(tahmin3,y))

              precision    recall  f1-score   support

           1       0.83      0.86      0.84     51380
           2       0.86      0.80      0.83     30866
           3       0.80      0.80      0.80     17754

    accuracy                           0.83    100000
   macro avg       0.83      0.82      0.82    100000
weighted avg       0.83      0.83      0.83    100000



In [40]:
from sklearn.linear_model import LogisticRegression
l=LogisticRegression()
l.fit(x,y)

/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [41]:
tahmin4=l.predict(x)

In [42]:
confusion_matrix(tahmin4,y)

array([[45618, 21403, 15679],
       [ 7214,  7518,  1750],
       [  342,    77,   399]])

In [43]:
accuracy_score(tahmin4,y)

0.53535

In [44]:
x.shape

(100000, 25)

In [46]:
from sklearn.tree import DecisionTreeClassifier
d=DecisionTreeClassifier()
d.fit(x,y)
# overfitting undercutting

DecisionTreeClassifier()

In [47]:
tahmin5=d.predict(x)

In [48]:
accuracy_score(tahmin5,y)

1.0

In [49]:
confusion_matrix(tahmin5,y)

array([[53174,     0,     0],
       [    0, 28998,     0],
       [    0,     0, 17828]])

In [51]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier()
r.fit(x,y)

/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [52]:
tahmin6=r.predict(x)

In [53]:
accuracy_score(tahmin6,y)

0.99999

In [56]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x,y)

/Users/tugbakayhan/anaconda3/lib/python3.11/site-packages/sklearn/ensemble/_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier()

In [57]:
tahmin7=gb.predict(x)

In [58]:
accuracy_score(tahmin7,y)

0.70839

In [59]:
confusion_matrix(tahmin7,y)

array([[39817,  8440,  4884],
       [ 6766, 18316,   238],
       [ 6591,  2242, 12706]])